# Site settings
title: MrTsien Blog
SEOTitle: MrTsien的博客 | MrTsien Blog
header-img: img/home-bg-o.jpg
email: mrtsien@outlook.com
description: "关于软件设计开发、大数据、黑客与画家 | MrTsien，Web & Mobile Lover，BigData Engineer，SoftWare Designer | 这里是 @MrTsien 的个人博客，与你一起发现更大的世界。"
keyword: "MrTsien, MrTsien, MrTsien, mrtsien, MrTsien的博客, MrTsien Blog, 博客, 个人网站, 互联网, 大数据, 设计"
url: "mrtsien.github.io.git"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
# weibo_username:     
# zhihu_username: 
github_username:    mrtsien
# twitter_username:   
# facebook_username:  
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


#duoshuo settings
# duoshuo_username: _你的用户名_

# Disqus settings
disqus_username: mrtsien

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
ba_track_id: 2f6291b787c5f489eb1f9bac551b37cc

# Google Analytics
ga_track_id: 'UA-105069315-1'            # Format: UA-xxxxxx-xx
ga_domain: www.mrtsien.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，做做设计，<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/avatar-qql.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    # {
    #     title: "kunlng",
    #     href: "http://www.kunlng.com"
    # }
]
